### PR TITLE
Refactor code to use more sql and less java logic.

### PR DESCRIPTION
**Pull request by jaredscarr**
I think the point of this assignment is to show off our query skills. This PR removes the java filtering logic and pushes it into the query logic. This is also more accurate as the total average is no longer an integer.

added java docs
modified date prompt to be more specific.

### CODE REVIEW

**Comment by jaredscarr** [comment]
Below are some of the queries I used to verify the logic was correct in addition to comparing against what Derrek wrote


select product_Id, sum(quantity)
from transaction
where purchase_date between '2020-01-01' and '2023-12-01'
and product_Id = 49
group by product_Id;
-- verify the count of how many transactions for a product there are
-- make sure to pick a range that contains more than one entry to make sure the 
-- averages and sums are the expected results

-- see all products in date range
select avg(quantity), sum(quantity) from transaction
where purchase_date between '2020-01-01' and '2023-12-01';

-- count of specific product
select sum(quantity) / count(product_id) as avg_quantity from transaction where product_Id = 2
AND purchase_date between '2020-01-01' and '2023-12-01';

-- see the numbers instead of count for a specific product and date range
select sum(quantity) from transaction
where product_Id = 2
AND purchase_date between '2020-01-01' and '2023-12-01';

-- sanity check on quantity
select product.product_id, name, price, quantity from product
inner join transaction 
on product.product_id = transaction.product_Id
where product.product_id = 2
and purchase_date between '2020-01-01' and '2023-12-01';


-- select for the average quantity over all the products in the date range
select avg(range_avg.total) as total_avg
from (
	select sum(quantity) total
    from transaction as t
	where t.purchase_date between '2020-01-01' and '2023-12-01'
	GROUP BY t.product_Id
) as range_avg;

-- THIS IS THE END QUERY YOU WANT: 
select pop.product_Id, pop.name, pop.total, pop.trans_count
from (
	select totals.product_Id, totals.name, total, trans_count
	from (
		select t.product_Id, prod.name, sum(t.quantity) as total, count(t.product_Id) as trans_count from transaction as t
		inner join product as prod on t.product_Id = prod.product_id
        where t.purchase_date between '2020-01-01' and '2023-12-01'
		group by t.product_Id
	) as totals
) as pop
where pop.total < (
	select avg(range_avg.total) as total_avg
	from (
		select sum(quantity) total
		from transaction as t
        where t.purchase_date between '2020-01-01' and '2023-12-01'
		group by t.product_Id
	) as range_avg
);

**Comment by murphnomer** [comment]
I like this!  Let the database do the work so the program doesn't have to!

**Review by murphnomer — APPROVED** [review]
Looks correct to me.  I agree with Jared that for this class doing the math in the query is the right way to go and really just use Java for retrieving and displaying as much as possible.

**Comment by jaredscarr** [comment]
Oh this will probably break once the new sql script is run. I'll update it.

**Pull request merged**
